apiVersion: v1
kind: Service
metadata:
  name: dental-service
spec:
  selector:
    app: dental-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # same as your containerPort
  type: LoadBalancer
